apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stripe-app
  template:
    metadata:
      labels:
        app: stripe-app
    spec:
      containers:
        - name: stripe
          image: uonyeka/stripe:linux-amd64
          ports:
            - containerPort: 5003
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "4Gi"
